apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Nayannyk/demo-kube.git
      targetRevision: manifests
      path: monitoring
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.3.0
      helm:
        valueFiles:
          - $values/monitoring/kube-prometheus-stack-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Prune=false
